#!/usr/bin/env bash

#
# ZeXtras' Zimbra API for Zimlet building
# Copyright (C) 2017 ZeXtras S.r.l.
#
# This file is part of ZeXtras' Zimbra API for Zimlet building.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, version 2 of
# the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ZeXtras' Zimbra API for Zimlet building. If not, see <http://www.gnu.org/licenses/>.
#

work_dir=$( pwd )
src_dir=$( pwd )
ts_file_list=$( find . -name "*.ts" | LC_ALL=C sort)
cd ${work_dir}
ret_code=0

for i in ${ts_file_list};
do
    class_name=$( basename -s ".ts" ${i} )
    file_path=$( dirname ${i} )
    file_name="${file_path}/${class_name}.js"
    if [ -f "${file_name}" ]; then
        ts_exports=$( sed -rn -e 's/\/\*.*\*\///' -e '/^[[:blank:]]*\/\*/,/^[[:blank:]]*\*\//d' -e '/^[[:blank:]]*\/\//d' -e 's/.*export (abstract\ class|class|let|function|const) ([a-zA-Z0-9_]*).*/  exports.\2 = \2;/p' ${src_dir}/${i} | LC_ALL=C sort -u )
        js_exports=$( sed -rn -e 's/\/\*.*\*\///' -e '/^[[:blank:]]*\/\*/,/^[[:blank:]]*\*\//d' -e '/^[[:blank:]]*\/\//d' -e 's/.*exports\.([a-zA-Z0-9_]*).*/  exports.\1 = \1;/p' "${file_name}" | LC_ALL=C sort -u )
        only_ts=$( LC_ALL=C comm -2 -3 <(echo "${ts_exports}") <(echo "${js_exports}") )
        only_js=$( LC_ALL=C comm -1 -3 <(echo "${ts_exports}") <(echo "${js_exports}") )
        if [ -n "${only_ts}" -o -n "${only_js}" ]; then
            ret_code=1
            echo "${file_name}"
            if [ -n "${only_ts}" ]; then
                echo " | --- In TS Exports and missing in JS Exports ---"
                echo "${only_ts}" | sed 's/^/ | /'
            fi
            if [ -n "${only_js}" ]; then
                echo " | --- In JS Exports and missing in TS Exports ---"
                echo "${only_js}" | sed 's/^/ | /'
            fi
        fi
    fi
done
exit ${ret_code}
