define(["require", "exports"], function (require, exports) {
  "use strict";
  exports.XForm = XForm;
  exports._NONE_ = _NONE_;
  exports._LEFT_ = _LEFT_;
  exports._TOP_ = _TOP_;
  exports._RIGHT_ = _RIGHT_;
  exports._BOTTOM_ = _BOTTOM_;
  exports._CENTER_ = _CENTER_;
  exports._MIDDLE_ = _MIDDLE_;
  exports._INLINE_ = _INLINE_;
  exports._HIDE_ = _HIDE_;
  exports._BLOCK_HIDE_ = _BLOCK_HIDE_;
  exports._DISABLE_ = _DISABLE_;
  exports._SHOW_DISABLED_ = _SHOW_DISABLED_;
  exports._PARENT_ = _PARENT_;
  exports._SELF_ = _SELF_;
  exports._OPEN_ = _OPEN_;
  exports._CLOSED_ = _CLOSED_;
  exports._HIDDEN_ = _HIDDEN_;
  exports._SCROLL_ = _SCROLL_;
  exports._AUTO_ = _AUTO_;
  exports._VISIBLE_ = _VISIBLE_;
});
